# Generated by Django 5.2 on 2025-04-10 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_creattask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parentTask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sonTask',
        ),
        migrations.AddField(
            model_name='task',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtask', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignedTeams',
            field=models.ManyToManyField(to='tasks.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignedUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdTasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CreatTask',
        ),
    ]
