# Generated by Django 5.2 on 2025-04-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_parenttask_remove_task_sontask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
