# Generated by Django 5.2 on 2025-05-06 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='task_list',
            field=models.ManyToManyField(to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='statut',
            field=models.CharField(choices=[('privée', 'Privée'), ('publique', 'Publique')], default='privée', max_length=200),
        ),
    ]
