# Generated by Django 4.2.11 on 2025-05-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_team_members_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedTeams',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='tasks.team'),
        ),
    ]
